name: Show Environment Variables

on:
  workflow_dispatch:

jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write secrets to file
        run: |
          echo "APP_IDENTIFIER=$APP_IDENTIFIER" >> secrets.txt
          echo "FASTLANE_ISSUER_ID=$FASTLANE_ISSUER_ID" >> secrets.txt
          echo "FASTLANE_KEY=$FASTLANE_KEY" >> secrets.txt
          echo "FASTLANE_KEY_ID=$FASTLANE_KEY_ID" >> secrets.txt
          echo "GH_PAT=$GH_PAT" >> secrets.txt
          echo "MATCH_PASSWORD=$MATCH_PASSWORD" >> secrets.txt
          echo "TEAMID=$TEAMID" >> secrets.txt
        env:
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEAMID: ${{ secrets.TEAMID }}

      - name: Upload secrets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
